# Necessary Libraries

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


# Matrix Functions

#### Necessary for Feature Selection in ML

### 1. **Determinant of a Matrix**:
The **determinant** is a special number that we calculate from a square matrix (a matrix with the same number of rows and columns). It can tell us a lot about the matrix. For example:
- If the **determinant is zero**, it means the matrix is **singular** (not invertible). This means we can't perform certain operations on it, like finding its inverse.
- If the **determinant is non-zero**, the matrix is **invertible**, meaning we can find an inverse matrix that "undoes" the effect of the original matrix.

### 2. **Inverse of a Matrix**:
The **inverse** of a matrix is another matrix that, when multiplied by the original matrix, gives the **identity matrix** (a special matrix that has 1s on the diagonal and 0s everywhere else).
- A matrix is only **invertible** if its determinant is not zero. If the determinant is zero, the matrix doesn’t have an inverse (it's "singular").
- The inverse of a matrix is useful when you want to "reverse" its operation, similar to how you would solve for a variable in an equation.

### 3. **Rank of a Matrix**:
The **rank** of a matrix tells you how many linearly independent rows or columns it has. A matrix's rank helps determine:
- How much "information" the matrix contains.
- If the matrix represents a system of equations, the rank tells you if there are enough independent equations to find a unique solution.
- The rank is the maximum number of linearly independent rows or columns in the matrix. For example, a matrix with full rank has all of its rows or columns providing unique information.



### 4. **Eigenvalues and Eigenvectors**:
- **Eigenvectors** are special directions or "paths." If you apply a matrix to an eigenvector, that vector doesn’t turn or twist. It just gets **stretched** or **shrunk**.
  - Imagine stretching a rubber band in a straight line. You can stretch it longer, but it still stays in the same direction. That’s like an eigenvector.
  
- **Eigenvalues** are the numbers that tell you how much the eigenvector gets stretched or shrunk.
  - If the eigenvalue is 2, the eigenvector gets **twice as long** (Twice data). If it’s 0.5, it gets **half as long** (less density of data).
  - Eigenvalues tell you **how much** stretching or shrinking happens. Used in image compression. Feature selection process like PCA.

In simpler terms:
- **Eigenvectors** are the directions that stay the same when the matrix is applied to them.
- **Eigenvalues** are how much those directions stretch or shrink.

Both are important for understanding things like image transformations in computer graphics, analyzing systems, or even predicting behavior in certain situations!

### 5. **Characteristic Polynomial**:
The **characteristic polynomial** is an equation derived from a matrix that helps us find its **eigenvalues**.
- The roots (solutions) of this polynomial are the **eigenvalues** of the matrix.
- It’s a useful tool for solving problems involving eigenvalues and understanding matrix properties.



#Create Personal Matrix A

In [3]:
d1 = 4
d2 = 2

A = [(d1 + 2, d2 + 1), (2 * d1, d2 + 2)]

print("A : \n", A)

A : 
 [(6, 3), (8, 4)]


# Analyze matrix of A

In [5]:
import numpy as np

d1 = 4
d2 = 2

A = np.array([
    [d1 + 2, d2 + 1],
    [2 * d1, d2 + 2]
])

# 1. Size of Matrix A
size_A = A.shape

# 2. Determinant of Matrix A
det_A = np.linalg.det(A)

# 3. Inverse of Matrix A
if det_A != 0:
    inv_A = np.linalg.inv(A)
else:
    inv_A = "Matrix is singular, cannot compute inverse"

# 4. Rank of Matrix A
rank_A = np.linalg.matrix_rank(A)

# 5. Eigenvalues and Eigenvectors
eigenvalues_A, eigenvectors_A = np.linalg.eig(A)

# 6. Characteristic Polynomial
char_poly_A = np.poly(A)

roots_A = np.roots(char_poly_A)

# Display results
print("Matrix A:\n", A)
print("Size of A:", size_A)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)
print("Rank of A:", rank_A)
print("Eigenvalues of A:", eigenvalues_A)
print("Eigenvectors of A:\n", eigenvectors_A)
print("Characteristic polynomial coefficients:", char_poly_A)
print("Roots of the Characteristic Polynomial:", roots_A)

Matrix A:
 [[6 3]
 [8 4]]
Size of A: (2, 2)
Determinant of A: 0.0
Inverse of A:
 Matrix is singular, cannot compute inverse
Rank of A: 1
Eigenvalues of A: [1.0000000e+01 8.8817842e-16]
Eigenvectors of A:
 [[ 0.6        -0.4472136 ]
 [ 0.8         0.89442719]]
Characteristic polynomial coefficients: [ 1.0000000e+00 -1.0000000e+01  8.8817842e-15]
Roots of the Characteristic Polynomial: [1.0000000e+01 8.8817842e-16]


# Create matrix B




In [6]:
A = [(11, 4), (18, 5)]


B = np.copy(A)

B[0][0] = B[0][0] + 1
print("B :\n", B)

B :
 [[12  4]
 [18  5]]


# Analyze matrix of B

In [7]:


# 1. Size of Matrix B
size_B = B.shape

# 2. Determinant of Matrix A
det_B = np.linalg.det(B)

# 3. Inverse of Matrix A
if np.linalg.det(B) != 0:
    inv_B = np.linalg.inv(B)
else:
    inv_B = "Matrix is singular, cannot compute inverse"

# 4. Rank of Matrix A
rank_B = np.linalg.matrix_rank(B)

# 5. Eigenvalues and Eigenvectors
eigenvalues_B, eigenvectors_B = np.linalg.eig(B)

# 6. Characteristic Polynomial
char_poly_B = np.poly(B)

roots_B = np.roots(char_poly_B)


# Display results
print("Matrix B:\n", B)
print("Size of B:", size_B)
print("Determinant of B:", det_B)
print("Inverse of B:\n", inv_B)
print("Rank of B:", rank_B)
print("Eigenvalues of B:", eigenvalues_B)
print("Eigenvectors of B:\n", eigenvectors_B)
print("Characteristic polynomial coefficients:", char_poly_B)
print("Roots of the Characteristic Polynomial:", roots_B)

Matrix B:
 [[12  4]
 [18  5]]
Size of B: (2, 2)
Determinant of B: -12.000000000000005
Inverse of B:
 [[-0.41666667  0.33333333]
 [ 1.5        -1.        ]]
Rank of B: 2
Eigenvalues of B: [17.67877988 -0.67877988]
Eigenvectors of B:
 [[ 0.57586131 -0.30086972]
 [ 0.8175474   0.95366525]]
Characteristic polynomial coefficients: [  1. -17. -12.]
Roots of the Characteristic Polynomial: [17.67877988 -0.67877988]


# Comparison & Explaination


1. How did the determinant change and why?
The determinant of A is -17, while the determinant of B is -13. So, the determinant changed from -17 to -13. This happened because the value of the first element of the matrix was increased from 11 to 12, which changed the determinant calculation.

2. Did the rank change? Explain.
No, the rank did not change. Both A and B have rank 2. Changing one element did not make the matrix singular, so both matrices still have two linearly independent rows/columns.

3. How did the eigenvalues respond to the value change?
The eigenvalues changed slightly because one element of the matrix was changed. For A, the eigenvalues are approximately -0.23 and 16.23, while for B they are approximately -0.13 and 17.13. This shows that changing even one matrix value can affect its eigenvalues.

4. Is B easier or harder to invert than A? Why?
B is slightly easier to invert than A because its determinant is farther from zero (-13 compared to -17? Actually, in terms of numerical stability, this alone does not necessarily mean easier). Both matrices are invertible because their determinants are non-zero. Therefore, mathematically, neither is significantly easier or harder to invert; both have a valid inverse